# Generated by Django 6.0.8 on 2026-08-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('provider_product_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in the smallest currency unit.')),
                ('currency', models.CharField(choices=[('NPR', 'Nepalese Rupee'), ('USD', 'US Dollar')], default='NPR', max_length=3)),
                ('interval', models.CharField(choices=[('one_time', 'One time'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('provider_price_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='billing.product')),
            ],
            options={
                'ordering': ['product__name', 'amount'],
                'constraints': [models.CheckConstraint(condition=models.Q(('interval_count__gte', 1)), name='billing_price_interval_count_positive')],
            },
        ),
    ]
