# Generated by Django 6.0.8 on 2026-08-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_productfeature_limit_subscription_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcustomer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
