# Generated by Django 6.0.8 on 2026-08-23 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billingcustomer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='provider_invoice_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('one_time', 'One Time'), ('day', 'Daily'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20),
        ),
    ]
