# Generated by Django 6.0.8 on 2026-08-24 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_payment_provider_invoice_id_payment_invoice_and_more'),
        ('tenants', '0005_alter_invitation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='billingcustomer',
            name='billing_customer_provider_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='checkoutsession',
            name='billing_checkout_provider_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='billing_payment_provider_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='billing_subscription_provider_id_unique',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_tenant__9b948c_idx',
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='provider_customer_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='provider_session_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_invoice_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='provider_price_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider_product_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider', 'provider_subscription_id'], name='billing_sub_provide_1b17b2_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['processing'], name='billing_web_process_6a9d99_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingcustomer',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_customer_id__isnull', False)), fields=('provider', 'provider_customer_id'), name='billing_customer_provider_id_unique'),
        ),
    ]
