# Generated by Django 6.0.8 on 2026-08-25 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_checkoutsession_options_alter_payment_options_and_more'),
        ('tenants', '0005_alter_invitation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingcustomer',
            name='billing_customer_tenant_provider_unique',
        ),
        migrations.AddField(
            model_name='billingcustomer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='billingcustomer',
            constraint=models.UniqueConstraint(fields=('tenant', 'active'), name='billing_customer_single_active_per_tenant'),
        ),
    ]
