# Generated by Django 6.0.8 on 2026-08-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='The human-readable name of the tenant.', max_length=255, unique=True, verbose_name='Tenant Name'),
        ),
    ]
