# Generated by Django 6.0.8 on 2026-08-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_invitation_unique_pending_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
